name: Flask CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # STAGE 1: Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests with pytest
      run: |
        python -m pytest tests/ --cov=password_strength_checker --cov-report=xml
        
    - name: Upload test coverage
      uses: codecov/codecov-action@v3

  # STAGE 2: Build Validation
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate requirements
      run: |
        pip install -r requirements.txt
        pip check  # Verify no dependency conflicts
        
    - name: Verify Flask app starts
      run: |
        python -c "from app import app; print('App imported successfully')"

  # STAGE 3: Deploy to Azure
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'password-strength-checker'
        package: .
        runtime-stack: 'PYTHON|3.11'
        startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'
        
    - name: Configure Environment Variables
      run: |
        az webapp config appsettings set \
          --name password-strength-checker \
          --resource-group your-resource-group-name \
          --settings \
            MIN_WEAK=6 \
            MIN_STRONG=10 \
            SPECIAL_CHARS="!@#$%^&*" \
            WEBSITES_PORT=8000